### ISSUE TITLE
scottyAppT's parameters have changed

### ISSUE THREAD

**Issue by schell** [scotty-web/scotty-tls#2]
Or at least I think that's what has happened. If you try to build the scotty-tls package on hackage it breaks because of an extra parameter passed to `scottyAppT`. It's fairly easy to update:

```haskell
{-# LANGUAGE RankNTypes #-}

module Web.Scotty.TLS
    (  -- * A method for running Scotty over TLS
      scottyTLS
       -- * Transformer version
    , scottyTTLS
    , module Web.Scotty.Trans
    ) where

import Control.Monad               ((<=<))
import Control.Monad.IO.Class      (MonadIO (liftIO))
import Network.Wai                 (Response)
import Network.Wai.Handler.Warp    (Port, defaultSettings, setPort)
import Network.Wai.Handler.WarpTLS (certFile, defaultTlsSettings, keyFile, runTLS)
import Web.Scotty                  (scottyApp, ScottyM)
import Web.Scotty.Trans            (ScottyT, scottyAppT)

-- | Run a Scotty application over TLS
scottyTLS :: Port -> FilePath -> FilePath -> ScottyM () -> IO ()
scottyTLS port key cert = runTLS
  (defaultTlsSettings { keyFile = key , certFile = cert })
  (setPort port defaultSettings) <=< scottyApp

scottyTTLS :: (Monad m, MonadIO n)
           => Port -> FilePath -> FilePath -> (m Response -> IO Response)
           -> ScottyT t m () -> n ()
scottyTTLS port key cert runToIO s = do
    app <- scottyAppT runToIO s
    liftIO $ runTLS (defaultTlsSettings { keyFile = key, certFile = cert })
                    (setPort port defaultSettings)
                    app
```

**Comment by schell** [comment]
In most use cases the extra parameter tended to be the same as `runToIO` anyway, so it's a good change IMO.

**Comment by RyanGlScott** [comment]
Oops, I haven't had the chance to update the rest of `scotty-web` to reflect the changes made in `scotty-0.10`.

I fixed the issue on the GitHub repo. @xich, can you give me permission to upload a new version to Hackage? It looks like `scotty-hastache` is also broken, so I'll need to upload a new version of that at some point as well.

**Comment by xich** [comment]
I don't have maintainer access to `scotty-tls` on hackage. I believe @dmjio owns it.

**Comment by dmjio** [comment]
@schell @xich @RyanGlScott looks like this is already fixed on the github version, but not pushed to hackage (version 0.4.0.0). Now on hackage: http://hackage.haskell.org/package/scotty-tls

**Comment by schell** [comment]
:+1:
