### ISSUE TITLE
Possibility of redirecting http to https

### ISSUE THREAD

**Issue by HalosGhost** [scotty-web/scotty-tls#3]
Is there a simple way, through scotty with ScottyTLS, to have ``http://example.com`` automatically redirect to ``https://example.com``? If so (or if this is available as a wai middleware that I could not find), can it be added to the documentation? And if not, how hard would this be to add for the next release?

**Comment by HalosGhost** [comment]
So then… that's a “No”? :P

**Comment by dmjio** [comment]
Sorry, closed this is as I thought it was related to a separate pull request. I'm not sure how to do what you described off-hand using scotty-tls. But if I were you I'd use nginx as a load-balancer and have url rewrite urls do it for you. nginx could also terminate your SSL as well.

**Comment by HalosGhost** [comment]
Not a problem. I kind of did not think this would be possible without digging pretty deeply into Warp. Thanks!
